/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apresentacao;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import modelo.Controle;

/**
 *
 * @author david
 */
public class frmCadastro extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public frmCadastro() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngSexo = new javax.swing.ButtonGroup();
        jpDadosCadastrais = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        txfNome = new javax.swing.JTextField();
        lblDataNascimento = new javax.swing.JLabel();
        lblCPF = new javax.swing.JLabel();
        lblRg = new javax.swing.JLabel();
        lblEstadoCivil = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();
        cbEstadoCivil = new javax.swing.JComboBox<>();
        lblDadosCadastrais = new javax.swing.JLabel();
        lbliconDados = new javax.swing.JLabel();
        lbliconContato = new javax.swing.JLabel();
        lblContato = new javax.swing.JLabel();
        lblTelefoneFixo = new javax.swing.JLabel();
        lblTelefoneCelular = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lbliconEndereco = new javax.swing.JLabel();
        lblEndereco = new javax.swing.JLabel();
        lblCEP = new javax.swing.JLabel();
        lblCidade = new javax.swing.JLabel();
        txfCidade = new javax.swing.JTextField();
        lblEstado = new javax.swing.JLabel();
        txfEstado = new javax.swing.JTextField();
        lblLogradouro = new javax.swing.JLabel();
        txfLogradouro = new javax.swing.JTextField();
        lblNum = new javax.swing.JLabel();
        txfNumero = new javax.swing.JTextField();
        txfBairro = new javax.swing.JTextField();
        lblBairro = new javax.swing.JLabel();
        lblComplemento = new javax.swing.JLabel();
        txfComplemento = new javax.swing.JTextField();
        ftfCep = new javax.swing.JFormattedTextField();
        txfEmail = new javax.swing.JTextField();
        txfCpf = new javax.swing.JTextField();
        txfRG = new javax.swing.JTextField();
        txfTelfixo = new javax.swing.JTextField();
        txfTelCelular = new javax.swing.JTextField();
        txfDataNascimento = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNome.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblNome.setForeground(new java.awt.Color(255, 102, 153));
        lblNome.setText("Nome");

        txfNome.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txfNome.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        lblDataNascimento.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblDataNascimento.setForeground(new java.awt.Color(255, 102, 153));
        lblDataNascimento.setText("Data de Nascimento");

        lblCPF.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblCPF.setForeground(new java.awt.Color(255, 102, 153));
        lblCPF.setText("CPF");

        lblRg.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblRg.setForeground(new java.awt.Color(255, 102, 153));
        lblRg.setText("RG");

        lblEstadoCivil.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblEstadoCivil.setForeground(new java.awt.Color(255, 102, 153));
        lblEstadoCivil.setText("Estado Civil");

        btnCadastrar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnCadastrar.setForeground(new java.awt.Color(255, 102, 153));
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(255, 255, 255), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        cbEstadoCivil.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cbEstadoCivil.setForeground(new java.awt.Color(255, 102, 153));
        cbEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Solteiro", "Casado", "Separado", "Divorciado", "Viúvo" }));
        cbEstadoCivil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEstadoCivilActionPerformed(evt);
            }
        });

        lblDadosCadastrais.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblDadosCadastrais.setText("Dados Cadastrais");

        lbliconDados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-usuário-50.png"))); // NOI18N
        lbliconDados.setText("jLabel3");

        lbliconContato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-telefone-50.png"))); // NOI18N
        lbliconContato.setText("jLabel5");

        lblContato.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblContato.setText("Contato");

        lblTelefoneFixo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblTelefoneFixo.setForeground(new java.awt.Color(255, 102, 153));
        lblTelefoneFixo.setText("Telefone Fixo");

        lblTelefoneCelular.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblTelefoneCelular.setForeground(new java.awt.Color(255, 102, 153));
        lblTelefoneCelular.setText("Telefone Celular");

        lblEmail.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(255, 102, 153));
        lblEmail.setText("Email");

        lbliconEndereco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-casa-50.png"))); // NOI18N
        lbliconEndereco.setText("jLabel3");

        lblEndereco.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblEndereco.setText("Endereco");

        lblCEP.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblCEP.setForeground(new java.awt.Color(255, 102, 153));
        lblCEP.setText("CEP");

        lblCidade.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblCidade.setForeground(new java.awt.Color(255, 102, 153));
        lblCidade.setText("Cidade");

        txfCidade.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txfCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfCidadeActionPerformed(evt);
            }
        });

        lblEstado.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblEstado.setForeground(new java.awt.Color(255, 102, 153));
        lblEstado.setText("Estado");

        txfEstado.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        lblLogradouro.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblLogradouro.setForeground(new java.awt.Color(255, 102, 153));
        lblLogradouro.setText("Logradouro");

        txfLogradouro.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        lblNum.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblNum.setForeground(new java.awt.Color(255, 102, 153));
        lblNum.setText("Numero");

        txfNumero.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        txfBairro.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        lblBairro.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblBairro.setForeground(new java.awt.Color(255, 102, 153));
        lblBairro.setText("Bairro");

        lblComplemento.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblComplemento.setForeground(new java.awt.Color(255, 102, 153));
        lblComplemento.setText("Complemento");

        txfComplemento.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        ftfCep.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ftfCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftfCepActionPerformed(evt);
            }
        });

        txfEmail.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        try {
            txfDataNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jpDadosCadastraisLayout = new javax.swing.GroupLayout(jpDadosCadastrais);
        jpDadosCadastrais.setLayout(jpDadosCadastraisLayout);
        jpDadosCadastraisLayout.setHorizontalGroup(
            jpDadosCadastraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDadosCadastraisLayout.createSequentialGroup()
                .addGroup(jpDadosCadastraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpDadosCadastraisLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jpDadosCadastraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEstadoCivil)
                            .addComponent(cbEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(540, 540, 540)
                        .addGroup(jpDadosCadastraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblComplemento)
                            .addComponent(txfComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpDadosCadastraisLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lbliconDados, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(lblDadosCadastrais)
                        .addGap(172, 172, 172)
                        .addComponent(lbliconContato, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(lblContato, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110)
                        .addComponent(lbliconEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(lblEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpDadosCadastraisLayout.createSequentialGroup()
                        .addGap(397, 397, 397)
                        .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpDadosCadastraisLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jpDadosCadastraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpDadosCadastraisLayout.createSequentialGroup()
                                .addGroup(jpDadosCadastraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpDadosCadastraisLayout.createSequentialGroup()
                                        .addComponent(lblCPF)
                                        .addGap(119, 119, 119)
                                        .addComponent(lblRg, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(195, 195, 195)
                                .addGroup(jpDadosCadastraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblEmail))
                                .addGap(149, 149, 149)
                                .addGroup(jpDadosCadastraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNum)
                                    .addComponent(txfEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(44, 44, 44)
                                .addGroup(jpDadosCadastraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblBairro)
                                    .addComponent(txfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txfLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jpDadosCadastraisLayout.createSequentialGroup()
                                .addGroup(jpDadosCadastraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jpDadosCadastraisLayout.createSequentialGroup()
                                        .addGroup(jpDadosCadastraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txfRG, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jpDadosCadastraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lblNome)))
                                        .addGap(112, 112, 112)
                                        .addGroup(jpDadosCadastraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblTelefoneFixo)
                                            .addComponent(txfTelfixo)))
                                    .addGroup(jpDadosCadastraisLayout.createSequentialGroup()
                                        .addGroup(jpDadosCadastraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txfDataNascimento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(222, 222, 222)
                                        .addGroup(jpDadosCadastraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblTelefoneCelular)
                                            .addComponent(txfTelCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(149, 149, 149)
                                .addGroup(jpDadosCadastraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpDadosCadastraisLayout.createSequentialGroup()
                                        .addComponent(lblCEP)
                                        .addGap(140, 140, 140)
                                        .addComponent(lblCidade))
                                    .addGroup(jpDadosCadastraisLayout.createSequentialGroup()
                                        .addGroup(jpDadosCadastraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ftfCep, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblEstado))
                                        .addGap(44, 44, 44)
                                        .addGroup(jpDadosCadastraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblLogradouro)
                                            .addComponent(txfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jpDadosCadastraisLayout.setVerticalGroup(
            jpDadosCadastraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDadosCadastraisLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jpDadosCadastraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbliconDados)
                    .addComponent(lbliconContato)
                    .addComponent(lbliconEndereco)
                    .addGroup(jpDadosCadastraisLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jpDadosCadastraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDadosCadastrais)
                            .addComponent(lblContato)
                            .addComponent(lblEndereco))))
                .addGap(40, 40, 40)
                .addGroup(jpDadosCadastraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNome)
                    .addComponent(lblTelefoneFixo)
                    .addGroup(jpDadosCadastraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCidade)
                        .addComponent(lblCEP)))
                .addGap(6, 6, 6)
                .addGroup(jpDadosCadastraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftfCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfTelfixo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jpDadosCadastraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDataNascimento)
                    .addGroup(jpDadosCadastraisLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jpDadosCadastraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTelefoneCelular)
                            .addComponent(lblEstado, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblLogradouro, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGroup(jpDadosCadastraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpDadosCadastraisLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jpDadosCadastraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txfEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txfLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpDadosCadastraisLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txfTelCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpDadosCadastraisLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txfDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14)
                .addGroup(jpDadosCadastraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCPF)
                    .addGroup(jpDadosCadastraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblRg)
                        .addComponent(lblEmail))
                    .addGroup(jpDadosCadastraisLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jpDadosCadastraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNum, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblBairro))))
                .addGap(6, 6, 6)
                .addGroup(jpDadosCadastraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txfRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpDadosCadastraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpDadosCadastraisLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jpDadosCadastraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(32, 32, 32)
                .addGroup(jpDadosCadastraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpDadosCadastraisLayout.createSequentialGroup()
                        .addComponent(lblEstadoCivil)
                        .addGap(6, 6, 6)
                        .addComponent(cbEstadoCivil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(btnCadastrar))
                    .addGroup(jpDadosCadastraisLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(lblComplemento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txfComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpDadosCadastrais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpDadosCadastrais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ftfCepActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ftfCepActionPerformed
    {//GEN-HEADEREND:event_ftfCepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftfCepActionPerformed

    private void txfCidadeActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txfCidadeActionPerformed
    {//GEN-HEADEREND:event_txfCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfCidadeActionPerformed

    private void cbEstadoCivilActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cbEstadoCivilActionPerformed
    {//GEN-HEADEREND:event_cbEstadoCivilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbEstadoCivilActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCadastrarActionPerformed
    {//GEN-HEADEREND:event_btnCadastrarActionPerformed
        Controle controle = new Controle();
        List<String> listadadosPaciente = new ArrayList<>();
        listadadosPaciente.add("0");
        listadadosPaciente.add(txfNome.getText());
        listadadosPaciente.add(txfDataNascimento.getText());
        listadadosPaciente.add(txfCpf.getText());
        listadadosPaciente.add(txfRG.getText());
        listadadosPaciente.add(cbEstadoCivil.getSelectedItem().toString());
        listadadosPaciente.add(txfTelfixo.getText());
        listadadosPaciente.add(txfTelCelular.getText());
        listadadosPaciente.add(txfEmail.getText());
        listadadosPaciente.add(ftfCep.getText());
        listadadosPaciente.add(txfCidade.getText());
        listadadosPaciente.add(txfEstado.getText());
        listadadosPaciente.add(txfLogradouro.getText());
        listadadosPaciente.add(txfNumero.getText());
        listadadosPaciente.add(txfBairro.getText());
        listadadosPaciente.add(txfComplemento.getText());
        controle.cadastrarPaciente(listadadosPaciente);
        JOptionPane.showMessageDialog(null, controle.mensagem);
    }//GEN-LAST:event_btnCadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.ButtonGroup btngSexo;
    private javax.swing.JComboBox<String> cbEstadoCivil;
    private javax.swing.JFormattedTextField ftfCep;
    private javax.swing.JPanel jpDadosCadastrais;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblCEP;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblComplemento;
    private javax.swing.JLabel lblContato;
    private javax.swing.JLabel lblDadosCadastrais;
    private javax.swing.JLabel lblDataNascimento;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblEstadoCivil;
    private javax.swing.JLabel lblLogradouro;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNum;
    private javax.swing.JLabel lblRg;
    private javax.swing.JLabel lblTelefoneCelular;
    private javax.swing.JLabel lblTelefoneFixo;
    private javax.swing.JLabel lbliconContato;
    private javax.swing.JLabel lbliconDados;
    private javax.swing.JLabel lbliconEndereco;
    private javax.swing.JTextField txfBairro;
    private javax.swing.JTextField txfCidade;
    private javax.swing.JTextField txfComplemento;
    private javax.swing.JTextField txfCpf;
    private javax.swing.JFormattedTextField txfDataNascimento;
    private javax.swing.JTextField txfEmail;
    private javax.swing.JTextField txfEstado;
    private javax.swing.JTextField txfLogradouro;
    private javax.swing.JTextField txfNome;
    private javax.swing.JTextField txfNumero;
    private javax.swing.JTextField txfRG;
    private javax.swing.JTextField txfTelCelular;
    private javax.swing.JTextField txfTelfixo;
    // End of variables declaration//GEN-END:variables
}
